### ISSUE TITLE
Blue Squares, Items in Squares, Crafting Results, and Inventory Bag not Rendering

### ISSUE THREAD

**Issue by Retr0MC** [hammy3502/immersive-mc#110]
Forge 40.1.51: 1.18.2
I don't really have any ideas on how to fix this and would appreciate help.
also I have made sure shaders are off.
I'm using ImmersiveMC 1.0.0 Beta2.1, MC VR API 1.4.0, and Architectury 4.9.84
I'm not using any other mods, Thank you in advance.

**Comment by hammy275** [comment]
Was able to reproduce this. Should have it fixed as the very last thing before 1.1.0 beta 3 :smile:

**Comment by Retr0MC** [comment]
Thank you. =D

**Comment by hammy275** [comment]
Fixed in https://github.com/hammy3502/immersive-mc/commit/4d29e25f2646b22cf97fd5437b1774e237ea5341 . Will be out with beta 3 in a few!

**Comment by Retr0MC** [comment]
Works like a charm, Thanks.
