### ISSUE TITLE
the crafting table bug is back

### ISSUE THREAD

**Issue by KaziiTheAvali** [hammy3502/immersive-mc#114]
currently in beta 3 whenever i put something in the right of the immersive crafting table it goes into the left and vice versa. i am on a rift s if that helps any

**Comment by KaziiTheAvali** [comment]
it is only right and left not up and down btw and it only started on beta 3. beta 2 was allright

**Comment by hammy275** [comment]
I'll look into it. Thank you so much!

**Comment by hammy275** [comment]
Thanks for the report! It's fixed now, and the fix will show up once ImmersiveMC 1.1.0 is out of beta! :)
