### ISSUE TITLE
Enable Non VR crafting talbe interactions in VR

### ISSUE THREAD

**Issue by boneblow** [hammy3502/immersive-mc#134]
I don't know if this is already a thing I just didn't find yet but, it would be awesome if you were able to just right click (whatever the interact key in VR is)  the blue boxes on a crafting table (or any block with blue boxes) to place the items like you do without the VR-Api.

**Comment by hammy275** [comment]
That's a really good idea! I'll try to have that implemented very soon!

As an implementation detail, I'll add a setting for VR users that, when enabled, allows you to right click blue boxes in addition to "placing" the items in them.

**Comment by hammy275** [comment]
Support for this is added now, and will be released in a future ImmersiveMC update (1.1.3, most likely). Thanks again for the suggestion! :)
