### ISSUE TITLE
cant open bag

### ISSUE THREAD

**Issue by LuigiPlayer1** [hammy3502/immersive-mc#146]
in the guide it says for me to bind the open/close bag to the radial settings but that action dosent exist 
I cant find it

**Comment by hammy275** [comment]
It should definitely be there. There are two categories for ImmersiveMC, one called "ImmersiveMC Bindings" and one called "ImmersiveMC VR Bindings". Make sure you've looked in the latter category!

Let me know if you can't find it still!

**Comment by LuigiPlayer1** [comment]
@hammy3502 where is the immersiveMc VR bindings located, because its not in my key binds section and its not in the radial menu, I just cant find them for some reason

**Comment by hammy275** [comment]
At least in the regular controls menu, they should be directly below "Miscellaneous" assuming you don't have any other mods installed besides ImmersiveMC and its dependencies.

If you do have other mods, it's going to be somewhere, and I can't really say where. I'd make sure to look pretty closely, as the category only has 1 key in it. If it helps, the key is mapped to "F23" by default, so looking out for that may help.

**Comment by LuigiPlayer1** [comment]
@hammy3502 just doble checked and there is no section regarding imersive mc even when I only have it, could it be the architectury version??
or is it a bug
ps:: below miscellaneos there is only the GUI section

**Comment by hammy275** [comment]
That's really strange. To ask you a couple questions:
- What version of each mod (ImmersiveMC and its dependencies) are you using? If you want, feel free to also just send an image of your `mods` folder instead.
- What modloader (Forge or Fabric) are you using, and which version of it?
- Does pressing the "comma" key while in the world open the config screen?

Thanks!

**Comment by LuigiPlayer1** [comment]
@hammy3502 thanks for all of your help here are the answers:

![Screenshot 2022-12-26 205831](https://user-images.githubusercontent.com/121455369/209583010-1ff2df00-392d-4b8f-b680-148a4c8e687c.png)

I use forge 43.1.1

the comma does indeed open the config screen but I dont know if there were suppost to be key binds in there

**Comment by hammy275** [comment]
That's strange; the keybinds are defeinitely working then. I'll take a look and see what's going on, thanks!

**Comment by hammy275** [comment]
Thank you for raising this to my attention! I was able to get the bug reproduced! Now it comes down to fixing it lol

**Comment by hammy275** [comment]
@LuigiPlayer1 I was able to track the issue down; you'll want to upgrade to Architectury 6.2.46 or higher. I'll add that as a minimum version to ImmersiveMC so this issue doesn't pop up again.

Thanks again for the bug report! :)

**Comment by LuigiPlayer1** [comment]
@hammy3502 thank you so much your are a life saver and a wonderful mod creator cant wait for more of your mods 
fly high

**Comment by hammy275** [comment]
Closed by https://github.com/hammy3502/immersive-mc/commit/e347c458b0d3412dac7385e2673cc25a81a95e8a
