### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by aeluabik** [hammy3502/immersive-mc#152]
I always dreamt of a more immersive VR, I usually had dream of it coming easier to hytale, due to the modding support the team plans to provide. However, I came across this mod, which is fantastic. 
So I decided to tell my ideas that I have always expected for a VR mod and the developers can see if any is cool.
1. Carrying things and building: 
You know, VR tends to be a more slow-paced experience, and I know Minecraft tends to be fast (I mean, you can build a castle with bare hands in minutes). However, it is not because gameplays currently works like this that it must stay this way. 
I do think numbers could be removed and the whole experience become visual. A good example of a game that does this is hydroneer, you can carry things around, place them on buckets, vehicles. I think Minecraft could work that way: we could use both our hands, sacks, carts, pets, minecarts, create aeronautic vehicles that are coming, create transportation in order to carry wood, stone, minerals, etc. This gives a whole new meaning to logistics.
You could keep the backpack, except it would have limited capacity to the physical size and weight of things.
2. Crafting and tools:
A nice idea would be to use tools to shape ingredients. As an example, you could pickup the saw in the crafting table and saw a log  into planks. These planks could actually be items, not blocks, that you use a hammer to assemble into a plank block, by placing it on the desired location, then hammering. Stone could drop rubble, that can them be joined if placed on the ground with clay.
I know these ideas would make building a lot harder and slow, but it can be overcome if other players help or npcs, like the ones in minecolonies. 
3. Blocks and item Physics
4hese ideas actually require blocks to be actual physical things, so it would be important to have them being interactable and pushable by touching, be it with character body or hands.

**Comment by hammy275** [comment]
I really see the enthusiasm you have for making Minecraft a much more immersive and VR-centric mod, and I would honestly like to see it too! However, it honestly seems well beyond the scope of ImmersiveMC, between it really not working with non-VR users, and massively changing the game, probably breaking a lot of mod compatibility along the way. Additionally, having item specific interactions is a massive amount of work for just me, and seems better tackled by a mod like [ImmersiveCraft](https://www.curseforge.com/minecraft/mc-mods/immersive-craft)

Thank you again for the suggestions, though! :)
