### ISSUE TITLE
Crashes at launch

### ISSUE THREAD

**Issue by ZillyYT** [hammy3502/immersive-mc#153]
I questcraft then I click login to Microsoft then I click play then I questcraft closes is there a way to fix this?
(This also happens with the other mod that is needed to run this mod I’ve tried both individually and they both crash when run together or by themselves)

**Comment by hammy275** [comment]
Please make sure to install all the dependencies. Did you install Forge Config API Port and the Fabric version of Architectury API?

**Comment by ZillyYT** [comment]
Thank you I didn’t realize that I needed all 3 for vr and not just the single vr required one
