### ISSUE TITLE
Immersive trapdoors

### ISSUE THREAD

**Issue by S0apyy** [hammy3502/immersive-mc#172]
immersive trapdoors like doors and fence gates, for vr players.

Since there's already door and fence gate immersives this would be great.

**Comment by hammy275** [comment]
Sounds good to me!

**Comment by hammy275** [comment]
Forgot to close this when it was implemented yesterday, but this is now added! Immersive trapdoors will appear in the next ImmersiveMC version released (1.5.0 Beta 2).
