### ISSUE TITLE
I have placement mode set to one item, but it still places the whole stack in one click

### ISSUE THREAD

**Issue by slushieuwu** [hammy3502/immersive-mc#177]
![image](https://user-images.githubusercontent.com/86991346/212579043-76303308-10b8-49e1-978a-0ca7c7879525.png)
![image](https://user-images.githubusercontent.com/86991346/212579056-4f387195-20df-43de-915c-510f62000f5f.png)

**Comment by hammy275** [comment]
What version of ImmersiveMC and which mod loader are you using and on what Minecraft version?

And also, did you also have left click held down?

**Comment by slushieuwu** [comment]
> What version of ImmersiveMC and which mod loader are you using and on what Minecraft version?
> 
> And also, did you also have left click held down?

1. I think latest imc, quilt and 1.19.2
2. No

**Comment by hammy275** [comment]
That's really strange, I'll try to dig into what's happening. Thanks!

**Comment by hammy275** [comment]
@DmanMC , if you don't mind, in your `config/immersive_mc.toml`, what's the value you have for `placement_mode`?

**Comment by slushieuwu** [comment]
placement_mode = 0

**Comment by hammy275** [comment]
Huh. Are you playing single player or in a multiplayer world? And are you in VR, out of VR, or both?

**Comment by slushieuwu** [comment]
nonvr, singleplayer, and it was working fine at some point recently so idk what happened

**Comment by hammy275** [comment]
Dumb question. If you change it to other values (place a quarter, place half, etc.), are those ones also correct, or are they mismatched. If so, what are they mismatched to?

**Comment by slushieuwu** [comment]
yep happens with other values too

**Comment by hammy275** [comment]
For all values you end up placing a stack, you mean?

**Comment by hammy275** [comment]
I'm completely stupid. This is happening because chest-type immersives are programmed to put in their entire stacks for convenience. Will change this with #187

**Comment by slushieuwu** [comment]
Lmao 💀
