### ISSUE TITLE
Stop the game from crashing when trying to open the bag in nonvr

### ISSUE THREAD

**Issue by slushieuwu** [hammy3502/immersive-mc#178]
i know it doesnt work in nonvr, which is why it crashes, but it just either just shouldnt do anything, or you can code the bag to work in nonvr, which i dont think is worth the hassle

**Comment by hammy275** [comment]
Bruh it crashes? LMAO.

In all seriousness, thanks for reporting this. Just for myself to know, the fix I'll do for this will be to check if we're in VR when we receive the bag's keypress, only opening the bag if we're in VR.
