### ISSUE TITLE
Z-fighting on anvil slots

### ISSUE THREAD

**Issue by EthanRStokes** [hammy3502/immersive-mc#208]
I noticed there is some z-fighting on the anvil immersion.

Minecraft version: 1.19.2
Mod version: 1.2.3
Vivecraft version: 0.0.14
Vivecraft mode: NONVR
MC VR API version: 2.1.1

Here are some screenshots showcasing the issue
![image](https://user-images.githubusercontent.com/39657565/221428817-98a8b1b0-099a-431e-8bbc-e2f3ad04db8b.png)
![image](https://user-images.githubusercontent.com/39657565/221428868-2648580b-7aa9-49aa-a6b3-e59a620338cd.png)

**Comment by EthanRStokes** [comment]
I noticed this bug also applies on the smithing table.

**Comment by hammy275** [comment]
Thanks! Will fix this for 1.3.0.

That said, I should be able to fix this by shrinking the Anvil/Smithing Table boxes a bit. For clarity, the anvil and smithing table internally share the majority of the rendering code
