### ISSUE TITLE
Default inventory UI opens instead of backpack

### ISSUE THREAD

**Issue by FredDoesStuff** [hammy3502/immersive-mc#211]
Oculus Quest, using Vivecraft
Pressing X on the Oculus Controller (Which I believe is the keybind for the backpack) opens the default minecraft inventory ui instead of the backpack.
I've checked my settings, the Bag option is enabled.
I tried rebinding it in keybinds but it won't accept X as a viable button press

**Comment by FredDoesStuff** [comment]
Update, it does work with radial menu however its a shame I can't use the inventory button to open the bag instead.

**Comment by hammy275** [comment]
This is mainly an issue with the fact that Questcraft doesn't support key rebinding easily.

There is technically a way to do it through a config file unique to QC, but I'm not familiar with the process. People under standard Vivecraft are able to remap using SteamVR's bindings (which obviously isn't on the Quest, hence probably why QC doesn't have keybind remapping).

May want to take a look at #199 . Grabbing it from the back is currently planned

**Comment by FredDoesStuff** [comment]
I stated I was using Vivecraft instead of Questcraft, but I assume Quest isn't able to map button presses that Steam can recognize. Good to know backpacks will recieve better controls soon, this mod is already incredible.

**Comment by hammy275** [comment]
My bad!

I'm not too familiar with how to configure it, but there's a "Modded" tab somewhere in SteamVR bindings where you can select ImmersiveMC (and other modded) controls. I'd imagine it works with Quest controllers, but I haven't tested yet
