### ISSUE TITLE
Crafting table will not return empty bucket for recipes reqires water/milk as ingredient

### ISSUE THREAD

**Issue by TowardtheStars** [hammy3502/immersive-mc#212]
As title said, recipes like dough from Farmer's Delight and cake from vanilla Minecraft requires a fluid in bucket (or other containers, like bottles, etc. if moded), but using non-GUI style crafting will consume these containers when they should be returned.

Affected Minecraft version: 1.19.2-forge-43.2.4
Immersive MC version: 1.2.3-1.19.2
Architectury API version: 6.5.69-forge

**Comment by hammy275** [comment]
Thank you so much for pointing this out! :)
