### ISSUE TITLE
First Person Model Mod

### ISSUE THREAD

**Issue by Mister-16** [hammy3502/immersive-mc#221]
I would absolutely love to see compatibility/standalone addition of a first person model visible on the player, it'd really add to the immersion. doesn't have to be anything as advanced as bonelab's body system, just something to render the body underneath and show animations.

sorry if this is the wrong place to suggest!

**Comment by hammy275** [comment]
No worries!

This is definitely more of a Vivecraft thing, and they've already said it probably won't be happening (I forget if for a while or if it won't happen at all). Main reason being that such a mod for doing that already exists and works outside of VR, so it's more of a mod compatibility thing.

It's also pretty extensive code wise to how Minecraft would have to change, which I'd rather leave to Vivecraft
