### ISSUE TITLE
I can't open bag and nothing works

### ISSUE THREAD

**Issue by MrDuckTheFifth** [hammy3502/immersive-mc#222]
I am using VR and downloaded all the libs for VR and everything but when I boot up the game nothing is working when I tried to open the bag with the radial it did nothing, when I tried to craft ther was no UI it was just the normal menu. Can someone please help me fix it I spent an hour trying to get VR to even work with Minecraft and just wanted to play Minecraft in VR.

**Comment by MrDuckTheFifth** [comment]
I found out that everything works its just that there is no UI showing. I would still like some help though.

**Comment by hammy275** [comment]
That sounds like you don't have mc-vr-api installed properly. Make sure you install it for the same Minecraft version and modloader.

That said, if you need support, join the Discord instead: https://discord.gg/gZP6xjMtgW
