### ISSUE TITLE
Shield does not work

### ISSUE THREAD

**Issue by Dov47** [hammy3502/immersive-mc#226]
My shield does not work while trying to physically block, only when holding the rmb bind on controller. Is there a specific pose I have to take to block?

**Comment by hammy275** [comment]
You shouldn't need a specific pose. That said, if you're left-handed or using reverse hands, make sure you're on ImmersiveMC version 1.3.0 or later.

Got some feedback from someone else though that shield blocking feels a bit off (mainly with projectiles like skeleton arrows), so I'll try to improve that

**Comment by Dov47** [comment]
Ah, that is right I am lefthanded. I was using 1.2.2 but when I tried updating I am getting an error:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'immersivemc'!

do you know which of these mods I should update/remove to make it work?
![image](https://user-images.githubusercontent.com/128622325/227197482-a8b99c9d-d064-41dc-ab15-acc52f5f2966.png)

**Comment by Dov47** [comment]
Ok, I updated all files listed as required on forge page and it seems to work now!
