### ISSUE TITLE
Bug when placing blocks onto blocks with inventory.

### ISSUE THREAD

**Issue by Taz-Wolf** [hammy3502/immersive-mc#229]
When crouch+right clicking to place a block onto a block that has a inventory, such as a chest, brewing stand, hopper, ect, the placed block will instantly break and the gui for the block with an inventory will open. This issue is present in at least both 1.3.0 and 1.3.1 in both vr and flatscreen mode.

**Comment by hammy275** [comment]
This is intentional as to allow shift clicking to enter a GUI even with the immersive up (such as for immersives like Shulker Boxes, that have no way to open the vanilla UI). You can disable this by turning off "Bypass Immersion When Crouching" in ImmersiveMC's settings
