### ISSUE TITLE
the bag wont open

### ISSUE THREAD

**Issue by zmanbro** [hammy3502/immersive-mc#232]
for some reason it wont let me open the bag i tried to open it by the vive craft Radial menu it wont open even and i dont know if there is another way to open it

**Comment by hammy275** [comment]
Please join the ImmersiveMC Discord (https://discord.gg/gZP6xjMtgW) for support.

That said, make sure you have mc-vr-api updated to the latest version (or to 2.1.1 if you're on ImmersiveMC 1.2.x), and is for the same modloader
