### ISSUE TITLE
problem with keybind backpack

### ISSUE THREAD

**Issue by bennballler** [hammy3502/immersive-mc#234]
I can't use the backpack feature in vr because it not keybinded and I can't use the steamvr keybinding becauses it not in there

**Comment by hammy275** [comment]
The GitHub is not for support, head to the Discord for that.

That said, if you read the wiki for the Bag https://immersivemcwiki.hammy275.com/vr/bag.html , it mentions how you should bind it to the radial menu. Do that to access the bag.
