### ISSUE TITLE
Crafting table is way off, and most features do not work

### ISSUE THREAD

**Issue by Adidiii** [hammy3502/immersive-mc#239]
[Video of the problem](https://drive.google.com/file/d/1dZ2VikN0BAMtmfA79RDaaXytc_kJCl6D/view?usp=sharing) 
I downloaded the mod (1.16.5) with the latest version of vrapi (also 1.16.5, so 1.4.0) and Vivecraft. I try a world that was created BEFORE the mod was installed. 
I place a crafting table in creative mode (I also tried survival mode), and the blue squares are on it. But I can't hover them.

Wierder, I can put my first in somewhere seemingly random, and the turn green and suddenly become usable. Any ideas?
I also tested with non-vr, it works perfectly

EDIT: I have tried with a world created after the mod was installed, it causes the same issues

**Comment by hammy275** [comment]
In short, the green boxes in VR are not based on your hand being close to or inside the box, but rather based on where your primary controller (your right hand in the case of the video) is pointing. This admittedly isn't that intuitive, but the green box is just a visual feature, and shouldn't impact your ability to actually use an immersive (placing items in, etc.).

Going to leave this open as I'll probably fix it so it makes more sense visually in VR

EDIT: Marking this as enhancement and bug as it appears like a bug but is more of a bad user experience.

**Comment by Adidiii** [comment]
Well, I can't right click place items either, and I can't set the open bag feature in the settings. It's like the mod is installed and not installed at the same time

**Comment by hammy275** [comment]
Since you're in VR, you shouldn't be able to right click to place items (unless you change the option that allows you to do so), you need to move your hand holding the item (not just the item) into one of the boxes to place items.
The open bag feature should be somewhere when you go to change an item on the radial menu. You can verify that it'll show up there because it should also show up in the "Controls" menu, mapping to F23

**Comment by Adidiii** [comment]
I will try when I have time. I will inform you about further issues. Also, when you do apply the update, can you apply it to 1.16.5? That version hasn't been updated in ages... and it would let me access the fix to my problem

**Comment by hammy275** [comment]
I hope to one day port back everything to 1.16.5, but a lot of things are different from a code perspective in 1.16.5 in comparison to 1.18.2 (the transition of class names to MojMaps if you're familiar with it), so it's massively time consuming for what's becoming a relatively old version of the game. As someone who still plays 1.16.5 modpacks, I would backport it if I easily could

**Comment by Adidiii** [comment]
Ok, was just asking!

**Comment by Adidiii** [comment]
SOLVED! Turns out the mc-vr-api wasn't installed, and the mod didn't warn me

**Comment by hammy275** [comment]
Got it! Thanks for updating me :smile:

That said, it doesn't warn you, as the mod is also compatible outside of VR for some features. I should likely add a warning for VR users that they're missing MC VR API though

**Comment by Adidiii** [comment]
Just a reminder that it does remind you in the latest version, it's just 1.16.5

**Comment by hammy275** [comment]
Ah, gotcha.

1.16.5 is pretty much discontinued, so it will remain that way. Thanks for the reminder though; been a while since I used the 1.16.5 version in any capacity lol.

**Comment by Adidiii** [comment]
Yep, that's fine, although I don't imagine it to be difficult to implement a simple warning, but you do you
