### ISSUE TITLE
disable_vanilla_gui=true not working

### ISSUE THREAD

**Issue by kreezxil** [hammy3502/immersive-mc#255]
mc version: 1.19.4
forge version: 45.0.57
mod version: 1.3.2-1.19.4

enabling **disable_vanilla_gui** before and after singleplayer world creation doesn't work.

latest.log: https://paste.centos.org/view/7718d05b

video proof of being able to access the vanilla gui: https://youtu.be/OkGJ5QIOeO8

video proof that the config is set in the right spots: https://youtu.be/Y52rfmow1Wo

the config: https://paste.centos.org/view/f2bf3856

**Comment by hammy275** [comment]
Thanks for the bug report! Honestly not sure why it's happening, but I'll take a look into it! :smile:

**Comment by hammy275** [comment]
I can't seem to reproduce this. That said, in the config you pasted, `disable_vanilla_interactions` is set to `false`, rather than `true`, though I'm assuming that's just copy-pasting at the wrong time. 

This in theory shouldn't work, but can you give changing the option through the in-game settings a go? Enter a world, press "," (comma) on your keyboard, click "Customize Immersives", then set "Disable Vanilla Interactions" to ON. As an aside, make sure you're editing the config while the game is closed.

**Comment by kreezxil** [comment]
odd, could be a problem with vscodium, I swore I had set and saved it. saved being the operative word. i'll give it another whirl.

**Comment by kreezxil** [comment]
really odd I'm looking at the config and it is most definitely set right.

completely unedited.
![image](https://github.com/hammy275/immersive-mc/assets/3880072/474fc94e-0b67-40ef-b61f-4e9407d18826)

**Comment by kreezxil** [comment]
i see the fpaste shows it as false, also odd.

**Comment by kreezxil** [comment]
so verifying the config being set to true and it didn't work

but trying what you said and then it did work when configuring the mod thru the client.

[Zombie Defense Industry-0000000001.zip](https://github.com/hammy275/immersive-mc/files/11445932/Zombie.Defense.Industry-0000000001.zip)
The export of the pack I'm working on just about 10 mods in it so far, so you can see if something is a known incompatiblity.

**Comment by hammy275** [comment]
That's seriously weird that it's only working when set in game.

Thank you for the pack export, will take a look when I can!

**Comment by hammy275** [comment]
Please let me know if this still happens on ImmersiveMC 1.5.0 Alpha 2 if you're available to.

**Comment by kreezxil** [comment]
Thank you so much for fixing this, Just test it and it's working like a charm. Now if you don't mind please port it to 1.20.1 and 1.20.4. :)

**Comment by hammy275** [comment]
Glad things are working now!

ImmersiveMC has been on 1.20.1 for a while, and the 1.20.4 version is currently only in alpha (meaning if you download from CurseForge, you need to enable the "Show alpha files" in the Files tab, and also you can expect more bugs since it's an alpha).

**Comment by kreezxil** [comment]
I don't mind bugs.
