### ISSUE TITLE
Quilt Builds

### ISSUE THREAD

**Issue by hammy275** [hammy3502/immersive-mc#256]
Quilt builds currently aren't shipped, and instead Quilt users have to use the Fabric downloads. Let's get dedicated Quilt builds!

**Comment by hammy275** [comment]
Going to be scrapping this from 1.4 for a few reasons:
- We already depend on Architectury API and Forge Config API Port, which both don't have Quilt builds anyways.
- 1.4 is coming out much later than I want it to be, so I'd rather focus on things that make major end-user changes
- I take very little advantage of the Fabric API that Quilt has to duplicate to my knowledge (don't know how much Architectury and Forge Config API Port utilize it), so I don't see any breakage with Quilt folks happening anytime soon,*

That said, this is absolutely _not_ off the table, and I very much want to see this issue through. Just that now isn't an ideal time for it.

*: If breakage does happen though, it'll be top priority to fix; Quilt users should be able to use ImmersiveMC. Just that making standalone Quilt builds isn't the highest priority since Fabric builds can be used while I get Quilt builds going.

**Comment by Adidiii** [comment]
I don't think anyone uses quilt 💀, and if they do, the fabric version should work fine, right?

**Comment by hammy275** [comment]
The Fabric version works fine (hence why this is a lower priority issue (see the comment above yours)). However, having a Quilt-specific build would be nice for people who use Quilt and for if/when Quilt breaks off from supporting Fabric compatibility on top of their own.

**Comment by Adidiii** [comment]
Makes sense, just don't stress too much about it.

**Comment by hammy275** [comment]
From the work in #307, I left Forge Config API Port as a requirement in `quilt.mod.json`. That should be removed when this issue is tackled.

**Comment by hammy275** [comment]
For the time being, I'm not going to be working on Quilt-specific builds. If they break off compatibility from Fabric mods, I will definitely reconsider, but for the time being, Quilt users should use Fabric builds of ImmersiveMC.

Note that this does NOT mean Quilt isn't supported! If ImmersiveMC does not work on Quilt, it is something that needs to be and will be fixed! Quilt is a supported platform, just that they should be using the Fabric version of ImmersiveMC instead of a standalone Quilt build.

**Comment by Adidiii** [comment]
I think that's probably the best solution
