### ISSUE TITLE
Bottle and Bucket Dipping

### ISSUE THREAD

**Issue by hammy275** [hammy3502/immersive-mc#260]
Dip bottles and/or buckets into water/cauldrons to fill/empty them.

To differentiate in-code between filling and emptying for cauldrons, filling should take place when the item is pointing up in any capacity (the 180-degree span of pointing up) while filling should only be done when pointing the item down in some regard (though not the full 180-degree span).

Should be implemented as a server-side tracker, as filling should be do-able from above the block, and it just makes more sense to handle it all server-side imo.

**Comment by Adidiii** [comment]
Would also be neat if you could place water by turning ur bucket all the way upside down, and with both hands if there are too many false positives.

**Comment by hammy275** [comment]
Implemented
