### ISSUE TITLE
Hotswitch Compatibility

### ISSUE THREAD

**Issue by hammy275** [hammy3502/immersive-mc#275]
ImmersiveMC wasn't originally built for the ability to switch in and out of VR without a restart. We need to massively bugcheck to make sure that we safely account for this! Can use dev mode in `mc-vr-api` as well!

Bugs known:

- [x] Switching out of VR while the bag is open crashes (fixed in https://github.com/hammy275/immersive-mc/commit/e915a405924d80995162b303f8aded331c893db6)
- [x] Mixins for throw rendering has a bad target. Should add another one.
- [x] Backpack prevention mixin has a bad target. Should add another one.

**Comment by Adidiii** [comment]
Wait, how do you switch in and out of VR without a restart?

**Comment by hammy275** [comment]
Recent feature of Vivecraft in the 1.19.4/1.20.1 alpha builds, where if your headset detects that it's off your head, it'll switch you out of VR until it wakes up again

**Comment by Adidiii** [comment]
Oh, I'm still playing 1.19.2 because of mods XD!

**Comment by hammy275** [comment]
Wrapped this up in https://github.com/hammy275/immersive-mc/commit/56f6248c72bbbae80b6298c01cf763edc2fd8be4 (and of course will be ported up to 1.20.x). Will downport to previous versions once Vivecraft hotswitch compat is out for earlier versions
