### ISSUE TITLE
Server crash on anvil item take-out

### ISSUE THREAD

**Issue by dadospeedy** [hammy3502/immersive-mc#285]
[Client log](https://mclo.gs/kFAtabT)
[Server log](https://mclo.gs/aSocEUM)
[Server docker compose](https://github.com/dadospeedy/vr_mod_pack/blob/main/docker-compose.yaml)
[Full Mod list](https://github.com/dadospeedy/vr_mod_pack/blob/main/mod-list.md)

Game Version: 
**1.20.1**

Mod-Loader Version: 
**fabric-loader-0.14.21-1.20.1**

Mod file names:
- `fabric-api-0.86.0+1.20.1`
- `vivecraft-1.20.1-0.0.15-hotswitch-a5-fabric`
- `architectury-9.1.10-fabric`
---
- `immersivemc-1.4.0-beta1-1.20.1-fabric`
- `vrapi-3.0.6-1.20.1-fabric`
- `ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric`

Issue:
Server crashes when an item is enchanted through the immersive UI.

Can not confirm this issue in VR (right now).
Issue does not occur in single player.
Client just disconnects from server (does not crash.).

Steps to reproduce:
1. Playing in Flatscreen mode (Non-VR)
2. Placing a pickaxe (diamond) and an enchanting book (Eff 5) in an anvil (immersive UI)
3. server crashes when the enchanted item is taken out

**Comment by dadospeedy** [comment]
Note: 
1. It also occurs when repairing items using an anvil (so it is not the enchantment meta data causing the issue)
2. This issue (or one very closely related I imagine) also occurs when using an enchantment table:
[Server crash-log](https://mclo.gs/FdWRGen)
3. It also occurs when using the smithing table with armor trims:
[Server crash-log](https://mclo.gs/FDuEpnK)

I will refrain from testing more issues, as it always takes a bit to restart the server.
If you need further information though: Let me know.

**Comment by hammy275** [comment]
Likely the same issue as https://github.com/hammy275/immersive-mc/issues/284 . Seems to be an issue with rumble committing the major error of importing something that's client-side only on the server.
