### ISSUE TITLE
In non-VR mode sneak + right-click bug

### ISSUE THREAD

**Issue by bilejum** [hammy3502/immersive-mc#289]
In non-VR mode can't sneak + right-click on containers such as workbenches and furnaces Force placement of block such as torches
 
mc version: 1.19.4
fabric version: 45.0.57
mod version: 1.3.3

the config: https://paste.centos.org/view/a0c266a3
![image](https://github.com/hammy275/immersive-mc/assets/61893039/100b9b3a-6bde-4d16-a1b5-97e5fa990d9c)

**Comment by hammy275** [comment]
This is an intentional feature. You can disable it in [ImmersiveMC's settings](https://immersivemcwiki.hammy275.com/faq.html#q-how-do-i-access-immersivemc-settings).
