### ISSUE TITLE
I cant figure out keybinds (overall not working) qeust 1

### ISSUE THREAD

**Issue by Lolsz312** [hammy3502/immersive-mc#290]
Some buttons on controller arnt binding

**Comment by hammy275** [comment]
Please elaborate. What keybinds aren't binding, and what are you trying to do to bind them?

**Comment by Lolsz312** [comment]
I'm trying to unbind the invintorory key to replace w/ the bag open/close key. (i'm on vivecraft)

**Comment by Lolsz312** [comment]
Sorry I meant button on controller (not key).

**Comment by Lolsz312** [comment]
can you pleas help w/ some other gliches?

**Comment by hammy275** [comment]
That requires editing the SteamVR bindings, which I touch on a little bit on the ImmersiveMC wiki: https://immersivemcwiki.hammy275.com/vr/bag.html
