### ISSUE TITLE
Enchanting table not working

### ISSUE THREAD

**Issue by Vent0r** [hammy3502/immersive-mc#298]
I have an issue with the enchanting table, when I try to use it there aren't any blue square like in the crafting table. I don't know why that happens

**Comment by hammy275** [comment]
Make sure two blocks above the enchanting table are clear, and the blocks to the left and right of those blocks.

If you still need help, feel free to get in touch at the [ImmersiveMC Discord Server](https://discord.gg/gZP6xjMtgW)
