### ISSUE TITLE
Non-Cauldron Bottle and Bucket Dipping

### ISSUE THREAD

**Issue by hammy275** [hammy3502/immersive-mc#332]

**Comment by Adidiii** [comment]
Would this support the Inspirations mod's cauldron brewing?

**Comment by hammy275** [comment]
No, this is specifically for **non**-cauldrons, as cauldrons are already handled. If you want to see support for Inspirations mod's cauldron brewing, open an issue here or post about it in #suggestions on the Discord server.

**Comment by hammy275** [comment]
Done for 1.20.4, but needs to be ported down.

- [x] 1.20.2
- [x] 1.20.1
- [x] 1.19.4
- [x] 1.19.3
- [x] 1.19.2
- [x] 1.18.2

**Comment by hammy275** [comment]
This is done, and will be in the next version of ImmersiveMC (1.5.0 beta 2)!
