### ISSUE TITLE
2nd and Third row of Inventory in Chests and Barrels

### ISSUE THREAD

**Issue by CreeprVictor** [hammy3502/immersive-mc#336]
I can't access past the 1st row of inventory in chests or barrels. I can see the 2nd row in chests, but can't access it! The third row in the chest doesn't even show, and for the barrel, nor does the second show!

I'm not sure of how it works out in VR, as I haven't yet gotten one.

**Comment by hammy275** [comment]
You can left click while pointing at the chest to cycle between rows, both for VR and non-VR users. See https://immersivemcwiki.hammy275.com/both/chest.html

In the future, you can receive support on the ImmersiveMC Discord server.

**Comment by CreeprVictor** [comment]
> You can left click while pointing at the chest to cycle between rows, both for VR and non-VR users. See https://immersivemcwiki.hammy275.com/both/chest.html
> 
> In the future, you can receive support on the ImmersiveMC Discord server.

Really? Thanks! Now I know!
