### ISSUE TITLE
Can't put things in Bag - Can pull things out though

### ISSUE THREAD

**Issue by RedMageKnight** [hammy3502/immersive-mc#339]
Minecraft Version: 1.20.1
ImmersiveMC Version: 1.4.1
Loader: Fabric

I've noticed this more with trying to use the bag, I'll hit the button that's used to punch blocks while hovering over the placement icon to where it changes color to green but it won't add it to the bag. I can pull things out of the bag but can't put things back in. I've also noticed this with chests or any other container - I can take things out, but can't put things back in.

**Comment by hammy275** [comment]
The green box is not an indication in VR that you can interact with the slot. Make sure your hand, not just the item in your hand, is in the slot.

If you need further help, please join the ImmersiveMC Discord.
