### ISSUE TITLE
Unable to Place Blocks onto BlockEntities While Sneaking

### ISSUE THREAD

**Issue by Mafuyu33** [hammy3502/immersive-mc#365]
I found that when I'm sneaking (holding down the Shift key), I can't place blocks onto other block entities. For example, if I want to connect hoppers together, I can't do it easily.

**Comment by hammy275** [comment]
Duplicate of https://github.com/hammy275/immersive-mc/issues/229 . Check there for how to solve this.

**Comment by Mafuyu33** [comment]
My bad, I didn't check the previous issue.
