### ISSUE TITLE
Ender Chest Immersive

### ISSUE THREAD

**Issue by hammy3502** [hammy3502/immersive-mc#38]
Probably will use a majority of the code from `ChestImmersive`, or build on top of it.

**Comment by hammy3502** [comment]
Closed by https://github.com/hammy3502/immersive-mc/commit/ab1baa638ae3c67d8840f79723fee9f79f0afe1b

**Comment by fbklas** [comment]
@hammy275 my game crashes when simply looking (hovering over with the crosshair) over the enderchest. I'm in 1.5.0-beta1 [FORGE 1.20.1].

**Comment by hammy275** [comment]
This is known. See https://github.com/hammy275/immersive-mc/issues/418
