### ISSUE TITLE
ButtonPushTracker.tick hangs the Client Server Thread on Essentials

### ISSUE THREAD

**Issue by thejudge156** [hammy3502/immersive-mc#383]
Essential mod is known to sometimes cause networking issues, and in this case it appears to be an issue with Chunk Blocking. But it only happens to a connecting player, not the hosting player.

Thread Dump is attached.
[2024-04-09-1.log](https://github.com/hammy275/immersive-mc/files/14934933/2024-04-09-1.log)

**Comment by hammy275** [comment]
Another* essential incompatibility report: https://discord.com/channels/1061675558347489343/1228862187775328369/1228862187775328369

Also, of note, the hang happens at the first point ImmersiveMC interacts with a Minecraft level (or `world` in non-Mojmap land).

*: Has just occurred to me this is actually the same person lol. That said, this appears to be on 1.20.1 Fabric

**Comment by hammy275** [comment]
Adding to the above, part of the stack trace is also in c2me so perhaps something is happening there. The part of c2me that gets caught here is https://github.com/RelativityMC/C2ME-fabric/blob/ver/1.20.1/c2me-base/src/main/java/com/ishland/c2me/base/mixin/priority/MixinServerChunkManager.java#L50

**Comment by hammy275** [comment]
Going to close this, since I'm pretty sure this is a C2ME issue, which is something I don't plan to directly implement patches for. From previous testing, I wasn't able to replicate this under Essential, iirc. Do yell at me if this turns out to not be the case and still happens :)
