### ISSUE TITLE
Plugin port (Paper)

### ISSUE THREAD

**Issue by MiguVT** [hammy3502/immersive-mc#387]
I think one of the best things can be added is a Server-Side port for Paper, here is vivecraft plugin link: https://www.spigotmc.org/resources/vivecraft-spigot-extensions.33166/

**Comment by hammy275** [comment]
Hello!

I've gotten a request for this a few times, however it's a massive amount of effort that I personally don't have the willingness to do. If others want to take up the task, they're absolutely free to (ImmersiveMC is open source, after all!), and I'm happy to make adjustments on my end where needed.
