### ISSUE TITLE
BAg inventory

### ISSUE THREAD

**Issue by riderwac** [hammy3502/immersive-mc#421]
So, i recently bougth the meta quest 3 and i connect the quest to my pc and download the mods and inmersive mc and everything was perfect but my inventory is still the vanila one, everything of themod is perfect but this, is there any buttom or somethig i need to do?

**Comment by hammy275** [comment]
Please read the [opening the bag](https://immersivemcwiki.hammy275.com/vr/bag.html#opening-the-bag) section of the ImmerisveMC wiki.
