### ISSUE TITLE
Server crash with Lootr

### ISSUE THREAD

**Issue by crowmaticOrb** [hammy3502/immersive-mc#458]
When loading Lootr chests, sometimes the server will crash. Playing on 1.20.1 1.5.0-beta1
[crash-2024-09-13_21.32.05-server.txt](https://github.com/user-attachments/files/17000846/crash-2024-09-13_21.32.05-server.txt)

**Comment by hammy275** [comment]
This was fixed with #439, and will be in the next ImmersiveMC version (1.5.0 Beta 2) 😄
