### ISSUE TITLE
crash on 1.5.0-beta2 with mahou tsukai

### ISSUE THREAD

**Issue by stepsword** [hammy3502/immersive-mc#494]
[immersive-mc-mahou-crashlog.log](https://github.com/user-attachments/files/17528198/immersive-mc-mahou-crashlog.log)
Hi, a user gave me this crash log.. after some testing I narrowed it down to only happening when  immersive MC 1.5.0-beta2 is present. immersive MC 1.4.1 works fine though.

To replicate - install latest version of Mahou Tsukai and immersivemc-1.5.0-beta2-1.20.1-forge on Forge 47.3.11, and open creative mode and attempt to view the mahou tsukai creative tab (has a purple dagger as the icon). 

Game crashes immediately trying to render the bucket, I think. If there's something you need on my side that would help, let me know :)

**Comment by hammy275** [comment]
This falls under #475 (though the title of that issue is generally incorrect, it's for a lot of modded liquids under Forge), which I do plan to tackle for ImmersiveMC 1.5.0.

Going to close this as a duplicate, and follow #475 for updates (will change the title). Thank you for the report! :)
