### ISSUE TITLE
Barrels

### ISSUE THREAD

**Issue by hammy3502** [hammy3502/immersive-mc#55]
Items appear on the side where it opens, and is basically a vertical chest otherwise.

**Comment by hammy3502** [comment]
Clearing this from Beta 2, since Beta 2 is already becoming pretty big, so I'd rather have it done at a later point in time

**Comment by hammy3502** [comment]
Putting this on hold until I can find a good motion for closing barrels in VR.

**Comment by hammy275** [comment]
Based on #104 , we don't necessarily need to put a gesture action to this. Since this will be pretty similar to Shulker boxes functionality wise, and I have some fun helper functions to make this much easier in-place now, I'll add this in 1.1.0 beta 3.

**Comment by hammy275** [comment]
Moving away from guaranteed Beta 3. It looks like it's actually much closer to the chest, which has some fun mixin code to deal with.

**Comment by hammy275** [comment]
Resolve #140 first.

**Comment by hammy275** [comment]
Majority of it is done in https://github.com/hammy3502/immersive-mc/commit/0f94669e3de0a827446964037920e0e825794aaa . Only thing left is a VR hand motion to open from the handle and **a freaking config entry lol**

**Comment by hammy275** [comment]
Config part is done, just need the hand motion for opening
