### ISSUE TITLE
Crash if left then right click within a fraction of a second against anvil

### ISSUE THREAD

**Issue by Kaleidio** [hammy3502/immersive-mc#58]
https://pastebin.com/SrrhPv0s

**Comment by hammy3502** [comment]
Thank you for the bug report! I think I know what's going on, should hopefully get it solved for beta 2 :)

**Comment by hammy3502** [comment]
Thanks again for the bug report! I just committed a patch that should hopefully fix it.

Be on the lookout for it in beta 2! :)
