### ISSUE TITLE
Modded Support

### ISSUE THREAD

**Issue by crowmaticOrb** [hammy3502/immersive-mc#90]
It would be awesome if you could add support for the Crafting Station from Tinker's Construct, Iron Furnaces, and possibly Iron Chest (although they have non-uniform sizes so this might be difficult).

**Comment by hammy275** [comment]
Added support for IronFurnaces And the Tinker's Construct Crafting Station. They should be out soon:tm:!

**Comment by hammy275** [comment]
Going to think more on iron chests, as I don't think there's a good way to have so many items be presented intuitively to the user. As for the other two, they should be out soon, so I'm closing this issue. Thank you for the suggestions! :)
