### ISSUE TITLE
Immersive crafting seems to not be working for me

### ISSUE THREAD

**Issue by DaLordPlayz** [hammy3502/immersive-mc#98]
I installed the **1.18.2** versions of ImmersiveMC and MC VR API, but the immersives don't seem to be working. More specifically, the crafting. I also tried the **1.16.5** version, it didn't seem to work either. It might just be I can't figure out the controls. Not sure what to do.

**Comment by DaLordPlayz** [comment]
I'm gonna see if I can try to fix it on my end.

**Comment by hammy275** [comment]
Try following the instructions in VR section of the wiki for crafting [here](https://github.com/hammy3502/immersive-mc/wiki/Crafting-Table-Immersive) . If that doesn't work, let me know what you're trying to do, how you're doing it, and if anything weird pops up in logs.

**Comment by DaLordPlayz** [comment]
I've gotten the blue boxes for the crafting to show up before, I tried moving my hand close to the blue squares. I don't know if I had to press a button or something. They don't appear at all now, not sure why they stopped showing up.

**Comment by hammy275** [comment]
You have to look at the crafting table or have pointed at it recently to get them to show.

Make sure you have items in your hand, and you move the edge of your hand into the blue squares

**Comment by DaLordPlayz** [comment]
I'll try that if I can get the blue squares to show up again.

**Comment by DaLordPlayz** [comment]
I still can't get the blue squares to show. Does it not work correctly if starting a new world?

**Comment by DaLordPlayz** [comment]
This is on the 1.18.2 version, by the way

**Comment by hammy275** [comment]
It should work fine. Do you have any other mods, and does anything weird appear in your logs?

**Comment by DaLordPlayz** [comment]
The only mods I have are ImmersiveMC and MC VR API. I'll have to check the logs.

**Comment by DaLordPlayz** [comment]
The strange thing is why the blue squares stopped showing up, because, they have showed up before.

**Comment by DaLordPlayz** [comment]
I can't figure what changed. The blue squares still don't show up.

**Comment by DaLordPlayz** [comment]
I guess I could try it on 1.16.5 again.

**Comment by DaLordPlayz** [comment]
I can't see anything in the logs at all. It might just be hard for me to see specific stuff in the logs, but as far as I can tell there's nothing weird in the logs.

**Comment by DaLordPlayz** [comment]
I just tried the immersive crafting in non-VR and it works but the items and the blue squares don't show up.

**Comment by DaLordPlayz** [comment]
Which is strange because I have the blue squares set to ON

**Comment by DaLordPlayz** [comment]
Hello?

**Comment by DaLordPlayz** [comment]
I think I found out it works in VR too, but similar to flat, the blue squares don't show, even with the setting set to on

**Comment by DaLordPlayz** [comment]
Apparently, it has to do with my shader settings being set to internal instead of off.

**Comment by hammy275** [comment]
Ahhhh, I didn't realize internal shaders caused the blue boxes to not appear. Thanks for letting me know that!

ImmersiveMC is sadly only compatible with no shaders. I'm hoping to have that fixed at some point
